#!/usr/bin/env bash

. ./config.sh

set -e

export PATH=/system/bin/
export CLASSPATH="$OUTPUT_APK"

if [[ $VERBOSE == true ]]; then
  exec app_process -Xnoimage-dex2oat / \
    $(echo "$PACKAGE_NAME" | tr / .).Main "$@"
else
  exec app_process -Xnoimage-dex2oat / \
    $(echo "$PACKAGE_NAME" | tr / .).Main "$@" 2>/dev/null
fi
