package org.afetch;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.File;
import java.io.IOException;

import java.util.List;
import java.util.Map;
import java.util.HashMap;

import static org.afetch.Logger.Level.*;

public class Config {
  private String TAG = "Config";
  private Logger logger = Logger.getInstance();
  private String cfgDir = System.getenv("HOME") + "/.config/afetch";
  private String cfgPath = cfgDir + "/config.conf";
  private final Map<String, Boolean> configMap = new HashMap<>();

  private void loadConfig() {
    try {
      List<String> lines = Files.readAllLines(Paths.get(cfgPath));
      for (String line : lines) {
        line = line.trim();
        if (line.isEmpty() || line.startsWith("#")) continue;

        int hashIdx = line.indexOf('#');
        if (hashIdx != -1) {
          line = line.substring(0, hashIdx).trim();
        }

        String[] parts = line.split("=", 2);
        if (parts.length == 2) {
          configMap.put(parts[0].trim(), Boolean.parseBoolean(parts[1].trim()));
        }
      }
    } catch (IOException e) {
      logger.log(ERROR, TAG, e.getMessage());
    }
  }

  public boolean get(ConfigKey key) {
    loadConfig();
    return configMap.getOrDefault(key.getKey(), true);
  }

  public void createDeafultConfig() {
    String content = """
# This is autogenerated config
resolution=true
brand=true
vendor=true
uptime=true
DE=true
WM=true
CPU=true
GPU=true
memory=true
storage=true
CPUArch=true
battery=true # Battery need termux-api
apkCount=true
packageCount=true
IPV4=false # TODO: Not implemented yet
IPV4=false # TODO: Not implemented yet
""";

    if (!exists()) {
      createDirCfgIfNotExists();
    }

    try {
      Files.write(Paths.get(cfgPath), content.getBytes());
      logger.log(INFO, TAG, "Created config at: " + cfgPath);
    } catch (IOException e) {
      logger.log(ERROR, TAG, e.getMessage());
      e.printStackTrace();
    }
  }

  public String getCfgPath() {
    return cfgPath;
  }

  private boolean exists() {
    return new File(cfgDir).exists();
  }

  private void createDirCfgIfNotExists() {
    if (!exists()) {
      File dir = new File(cfgDir);
      dir.mkdirs();
    }
  }

}
