package org.afetch;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.File;
import java.io.IOException;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import static org.afetch.Logger.Level.*;

public class Config {
  private String TAG = "Config";
  private Logger logger = Logger.getInstance();
  private String cfgDir = System.getenv("HOME") + "/.config/afetch";
  private String cfgPath = cfgDir + "/config.conf";
  private final Map<String, Boolean> configMap = new HashMap<>();
  private final Set<String> overridden = new HashSet<>();

  private void loadConfig() {
    try {
      List<String> lines = Files.readAllLines(Paths.get(cfgPath));
      for (String line : lines) {
        line = line.trim();
        if (line.isEmpty() || line.startsWith("#")) continue;

        int hashIdx = line.indexOf('#');
        if (hashIdx != -1) {
          line = line.substring(0, hashIdx).trim();
        }

        String[] parts = line.split("=", 2);
        if (parts.length == 2) {
          String k = parts[0].trim();
          if (overridden.contains(k)) continue;
          configMap.put(k, Boolean.parseBoolean(parts[1].trim()));
        }
      }
    } catch (IOException e) {
      logger.log(ERROR, TAG, e.getMessage());
      e.printStackTrace();
    }
  }

  public boolean get(ConfigKey key) {
    // NOTE: i think better if loaded once
    if (new File(cfgPath).exists()) {
      loadConfig();
    }
    return configMap.getOrDefault(key.getKey(), true);
  }

  public void set(ConfigKey key, boolean value) {
    configMap.put(key.getKey(), value);
    overridden.add(key.getKey());
  }

  public void createDeafultConfig() {
    String content = """
# This is autogenerated config
logo=true             # show logo
resolution=true       # show resolution like 100x100 @ 60Hz
host=true             # show host including vendor, manufacturer and device
brand=true            # show brand
dpi=true              # show dpi like 360 (xhdpi)
uptime=true           # show uptime
DE=true               # show DE
WM=true               # show WM
CPU=true              # show CPU info including cores and name
GPU=true              # show GPU info including vendor, renderer
memory=true           # show memory info
swap=true             # show swap info
storage=true          # show storage info
ABI=true              # show supported abi
battery=true          # show battery including status, temperature and technology
apkCount=true         # show apk count including system apk
packageCount=true     # show package count including package manager name like pacman and dpkg
localIP=true          # show local ip address and network interface name
""";

    if (!exists()) {
      createDirCfgIfNotExists();
    }

    try {
      Files.write(Paths.get(cfgPath), content.getBytes());
      logger.log(INFO, TAG, "Created config at: " + cfgPath);
    } catch (IOException e) {
      logger.log(ERROR, TAG, e.getMessage());
      e.printStackTrace();
    }
  }

  public String getCfgPath() {
    return cfgPath;
  }

  private boolean exists() {
    return new File(cfgDir).exists();
  }

  private void createDirCfgIfNotExists() {
    if (!exists()) {
      File dir = new File(cfgDir);
      dir.mkdirs();
    }
  }

}
